image: maven:3.9.9-ibm-semeru-23-jammy

stages:
    - test-stage
    - coverage-stage
    - build-stage

domain-test-job:
    stage: test-stage
    script:
        - cd domain
        - mvn test
    artifacts:
        paths:
        - domain/target/classes
        expire_in: 1 day

api-test-job:
    stage: test-stage
    script:
        # - cd api
        # - mvn test
        - mvn install -pl '!api' -DskipTests
        - mvn test -pl api -am
    artifacts:
        paths:
        - api/target/jacoco.exec
        - api/target/classes
        expire_in: 1 day

domain-coverage-verification-job:
    stage: coverage-stage
    dependencies:
        - domain-test-job
    script:
        - cd domain
        - mvn scoverage:check

# api-coverage-verification-job:
#     stage: coverage-stage
#     dependencies:
#         - api-test-job
#     script:
#         # - cd api
#         # - mvn verify
#         - mvn install -pl '!api' -DskipTests
#         - mvn verify -pl api -am

domain-coverage-report-job:
  stage: coverage-stage
  needs:
    - job: domain-test-job 
  script:
    - cd domain
    - mvn scoverage:report
  coverage: '/Statement coverage\.\s*:\s*([\d.]+)%/'

# api-coverage-report-job:
#   stage: coverage-stage
#   needs:
#     - job: api-test-job 
#   script:
#     - cd api
#     - mvn jacoco:report
#     - cat target/site/jacoco/index.html | grep -o '<tfoot>.*</tfoot>'
#   coverage: /Total.*?([0-9]{1,3})%/

complete-build-job:
    stage: build-stage
    script:
        - mvn package